# KaGeneration config
# 注意：每个组所有矿石的概率合计应为 100!
# Note: The total probability of all ores in each group should be 100!

Language: "en_US"    # 内置语音文件 zh_CN, en_US | Available languages: zh_CN, en_US

Setting:
  # Whether to play sound and particle effects when placing blocks (true/false)
  # 使用指令place放置方块时是否播放音效和粒子效果 (true/false)
  play_block_effects: true

  # Whether to enable obsidian to lava bucket conversion (true/false)
  # 是否启用黑曜石转换岩浆桶功能 (true/false)
  get_lava_bucket: true

  # Whether to allow placing water buckets in the Nether (true/false)
  # 是否允许在下界放置水桶 (true/false)
  allow_water_in_nether: true

  # Whether to generate water from ice in the Nether (true/false)
  # 是否在下界通过破坏冰块生成水源 (true/false)
  generate_water_from_ice: true

Sound:
  # Sound effect when converting obsidian to lava bucket (Minecraft sound name)
  # 黑曜石转换岩浆桶时的音效 (Minecraft音效名称)
  lava_bucket: "ITEM_BUCKET_FILL_LAVA"

  # Sound effect when placing water bucket in the Nether (Minecraft sound name)
  # 在下界放置水桶时的音效 (Minecraft音效名称)
  water_in_nether: "ITEM_BUCKET_EMPTY"

  # Sound effect when breaking ice to generate water source (Minecraft sound name)
  # 破坏冰块生成水源时的音效 (Minecraft音效名称)
  ice_to_water: "BLOCK_GLASS_BREAK"

# 世界白名单（仅在这些世界生效） | World Whitelist (Only effective in these worlds)
World: # 留空[]则所有世界启用  | Fill in [] to enable all worlds
  - "skyblock"      # 直接匹配 #Directly match
  # - ".*_nether"      # 正则表达式匹配(名称以_nether结尾的世界) | Regular expression matching (world names ending in "_nether")
  # - "resource_.*"     # 正则表达式匹配(名称以resource_开头的世界) | Regular expression matching (world names starting with "resource_")
  # - ".*island.*"      # 正则表达式匹配(名称包含island的世界) | Regular expression matching (world with name including "island")


Generation:
  # 默认组（没有权限时使用） | Default group (used when no permission)
  default:
    priority: 0  #优先级 | Priority
    iron_ore: 3
    coal_ore: 5
    stone: 92

  # 等级1 - 需要权限 kageneration.level1 | Level 1 - Requires permission: kageneration.level1
  level1:
    priority: 1
    diamond_ore: 5
    iron_ore: 10
    coal_ore: 10
    stone: 70
    ia:tin_ore: 5  # ItemsAdder 方块支持 | ItemsAdder block support

  # 等级2 - 需要权限 kageneration.level2 | Level 2 - Requires permission: kageneration.level2
  level2:
    priority: 2
    diamond_ore: 10
    iron_ore: 15
    coal_ore: 15
    stone: 60

  # 等级3 - 需要权限 kageneration.level3 | Level 3 - Requires permission: kageneration.level3
  level3:
    priority: 3
    diamond_ore: 15
    iron_ore: 20
    coal_ore: 20
    stone: 45

  # 等级理论可无限添加，但优先级不允许相同，当拥有多个级别权限时，优先级最高的生效。
  # Levels can theoretically be added infinitely, but priorities must be unique. When having multiple level permissions, the one with the highest priority takes effect.