# KaGeneration 矿石生成配置
# 注意：每个组所有矿石的概率合计应为 100 ！
Setting:
  get_lava_bucket: false  # 是否启用空桶右键黑曜石转换岩浆桶
  allow_water_in_nether: false  # 是否允许在下界放置水桶
  generate_water_from_ice: true  # 是否允许在下界破坏冰块生成水源

# 世界白名单（仅在这些世界生效）
World:
  - skyblock
  - skyblock_world

Generation:
  # 默认组（没有权限时使用）
  default:
    priority: 0  #优先级
    iron_ore: 3
    coal_ore: 5
    stone: 92

  # 等级1 - 需要权限 kageneration.level1
  level1:
    priority: 1
    diamond_ore: 5
    iron_ore: 10
    coal_ore: 15
    stone: 70

  # 等级2 - 需要权限 kageneration.level2
  level2:
    priority: 2
    diamond_ore: 10
    iron_ore: 15
    coal_ore: 15
    stone: 60

  # 等级可无限添加，但优先级不允许相同，当拥有多个级别权限时，优先级最高的生效。