name: KaGeneration
version: '1.3'
main: org.katacr.kaGeneration.KaGeneration
api-version: '1.18'
description: '空岛插件:水流与岩浆交汇生成矿石'
author: ['Katacr', '小晓']
qq: 614401508
softdepend: [ItemsAdder]
github: 'https://github.com/Katacr/KaGeneration'

commands:
  kageneration:
    description: KaGeneration插件主命令
    aliases: [kg]
    usage: /kageneration reload

permissions:
  kageneration.reload:
    description: 允许重载插件
    default: op
  kageneration.place:
    description: 允许使用 /kg place 命令
    default: op
  kageneration.lavabucket:
    description: 允许使用空桶右键黑曜石转换为岩浆桶
    default: op
  kageneration.allowwater:
    description: 允许在下界放置水桶
    default: op
  kageneration.icebreak:
    description: 允许在下界破坏冰块生成水源
    default: op
  kageneration.help:
    description: 允许查看插件帮助
    default: true
  kageneration.info:
    description: 允许查看插件配置信息
    default: true
  kageneration.level1:
    description: 使用等级1矿石生成
    default: false
  kageneration.level2:
    description: 使用等级2矿石生成
    default: false
  kageneration.level3:
    description: 使用等级3矿石生成
    default: false
  kageneration.level4:
    description: 使用等级4矿石生成
    default: false
  kageneration.level5:
    description: 使用等级5矿石生成
    default: false