name: KaGeneration
version: '1.1'
main: org.katacr.kaGeneration.KaGeneration
api-version: '1.18'
description: '空岛插件:水流与岩浆交汇生成矿石'
author: ['Katacr', '小晓']
qq: 614401508
github: 'https://github.com/Katacr/KaGeneration'

commands:
  kageneration:
    description: KaGeneration插件主命令
    aliases: [kg]
    usage: /kageneration reload

permissions:
  kageneration.reload:
    description: 允许重载插件
    default: op
  kageneration.help:
    description: 允许查看插件帮助
    default: true
  kageneration.info:
    description: 允许查看插件配置信息
    default: true
  kageneration.level1:
    description: 使用等级1矿石生成
    default: false
  kageneration.level2:
    description: 使用等级2矿石生成
    default: false
  kageneration.level3:
    description: 使用等级3矿石生成
    default: false
  kageneration.level4:
    description: 使用等级4矿石生成
    default: false
  kageneration.level5:
    description: 使用等级5矿石生成
    default: false